### PR TITLE
Fix for new odoc

### PR DESCRIPTION
**Pull request by jonludlam**
This just renames the module `Migrate_parsetree_versions` to be
`Versions`. It was already exposed as `Migrate_parsetree.Versions`,
and this is not changed by this PR. The problem was that in the
generated alias file (migrate_parsetree__.ml-gen), dune puts in
a @canonical tag assuming that the module will be exposed with
the same filename - so previously that was:

    @canonical Migrate_parsetree.Migrate_parsetree_versions

but since it's actually exposed as `Migrate_parsetree.Versions`
this didn't resolve and odoc couldn't canonicalise references leading
to broken links.

Just renaming the module so it matches dune's expectations fixes
the problem.

Signed-off-by: Jon Ludlam <jon@recoil.org>

### CODE REVIEW

**Comment by ghost** [comment]
Hmm, not sure we can merge this right now. omp is still unwrapped, so this PR is effectively introducing a toplevel `Versions` compilation unit.

Given that it has been the "wrapped transition" mode for a while, i was thinking of releasing a 2.0.0 switching to the wrapped mode.

**Comment by jonludlam** [comment]
Ah, I hadn't noticed that. An alternative fix is to expose the module `Migrate_parsetree_versions` in the `Migrate_parsetree` module - possibly with a deprecation notice there too. Not too important if the 2.0.0 release is close though.

**Comment by ghost** [comment]
Following #95, the master is now using the normal wrapped mode. So this is fine to merge

**Comment by ghost** [comment]
Thanks for this PR! BTW, if you'd like to do the same for the other modules such as `Migrate_parsetree_driver` or `Migrate_parsetree_ast_io`, that would be welcome too :)

**Pull request merged**
