### PR TITLE
--dump-ast: preserve binary AST version

### LINKED ISSUE #79: --dump-ast: write the same version of AST that was read
So, if reading, e.g., a version 4.02 binary AST, writing with `--dump-ast` should produce a version 4.02 binary AST.

Right now, it produces an AST of whatever compiler version the driver was compiled with.

I believe this is the ultimate place where the decision to write the same version is not made:

https://github.com/ocaml-ppx/ocaml-migrate-parsetree/blob/b7f1862433e598aa9f91f9b96a5639f1caa301e7/src/migrate_parsetree_driver.ml#L429-L430

I guess we would need to note the source version on loading. On writing, we would need to migrate the AST to the target version (instead of to the current version, wherever this is done), and then write that. If the source version is not available (because we read a source file), we can write according to the version with which the driver was compiled, as now.

If this is approved, I can try to make the change.

### PR DESCRIPTION
**Pull request by aantron**
Resolves #79.

### CODE REVIEW

**Comment by aantron** [comment]
There will probably be a merge conflict if also merging #80. When I get an email about merging the first PR, I'll be happy to resolve any conflict in the other PR and rebase.

**Comment by ghost** [comment]
Looks good. Did you test this change?

**Comment by aantron** [comment]
Yes, I tested manually, and it's continuously tested in Bisect_ppx's CI, where OMP (and Bisect_ppx) is built with OCaml 4.08, and is processing BuckleScript's 4.02 ASTs, which the 4.02 BuckleScript is accepting. I previously also had CI installing BuckleScript 6.x, which is using 4.06 ASTs, and that worked, too.

**Comment by aantron** [comment]
After all the PRs are in, I'll check the resulting `master` again, so we can be more sure before any release.

**Review by ghost — APPROVED** [review]
Looks good

**Pull request merged**
