### PR TITLE
OMP 2.0

### PR DESCRIPTION
**Pull request by ceastlund**
Removes all functionality aside from versioned AST types and conversions between them. Most conspicuously missing are the `Versions` types that abstract over multiple versions, and the `Driver` functionality.

### CODE REVIEW

**Comment by ghost** [comment]
I had a look, it's a good start but we need to go a bit further with the removal:

- in the `Ast_xxx.ml` files, all that should be left are the `Asttypes`, `Parsetree` and `Config` modules
- the `migrate_xxx_yyy.ml` files can go away, they migrate `Ast_mapper.mapper` records and we only care about the parsetree types

We can also remove the manual entirely. The result library is very simple and a single README will be enough.

**Comment by ceastlund** [comment]
Okay, I've stripped out a lot more. Better?

**Review by ghost — APPROVED** [review]
Yes! I removed a few more things that were now unused, renamed the migration modules and fixed the cinaps setup while I was at it.

**Comment by ghost** [comment]
@ceastlund you can ignore the CI failure and merge, it's not related to this PR.

@dra27 we are getting random failures related to `ocaml-secondary-compiler`:

```
#=== ERROR while compiling ocaml-secondary-compiler.4.08.1-1 ==================#
# context              2.0.7 | linux/x86_64 | ocaml-base-compiler.4.04.0 | git+file:///home/opam/opam-repository
# path                 ~/.opam/ocaml-base-compiler.4.04.0/.opam-switch/build/ocaml-secondary-compiler.4.08.1-1
# command              ~/.opam/ocaml-base-compiler.4.04.0/.opam-switch/build/ocaml-secondary-compiler.4.08.1-1/./configure --prefix=/home/opam/.opam/ocaml-base-compiler.4.04.0/share/ocaml-secondary-compiler --libdir=/home/opam/.opam/ocaml-base-compiler.4.04.0/share/ocaml-secondary-compiler/lib --disable-debugger --disable-installing-bytecode-programs --disable-debug-runtime --disable-instrumented-runtime --disable-graph-lib
# exit-code            2
# env-file             ~/.opam/log/ocaml-secondary-compiler-6-98d1f9.env
# output-file          ~/.opam/log/ocaml-secondary-compiler-6-98d1f9.out
### output ###
# ls: cannot access '.': Operation not permitted
# configure: error: working directory cannot be determined
<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
+- The following actions failed
| - build ocaml-secondary-compiler 4.08.1-1
| - build topkg                    1.0.1
+- 
+- The following changes have been performed (the rest was aborted)
| - install conf-m4          1
| - install ocamlbuild       0.14.0
| - install ocamlfind        1.8.1
| - install opam-file-format 2.0.0
| - install uchar            0.0.2
+- 
<><> ocaml-secondary-compiler.4.08.1-1 troubleshooting ><><><><><><><><><><><><>
=> A failure in the middle of the build may be caused by build parallelism
      (enabled by default).
      Please file a bug report at https://github.com/ocaml/ocaml/issues
=> You can try installing again including --jobs=1
      to force a sequential build instead.
```

**Pull request merged**
