### PR TITLE
[wip] 4.08 omp parsetree

### PR DESCRIPTION
**Pull request by avsm**
I took a quick look at adding 4.08 support, and ran into a question: where does `gencopy` come from?  The ppx_tools repository has no such tool, and genlifter appears to be something else.

This PR currently just has a snapshot of ast_NEW.ml for 4.08 and some minor README instruction fixes

### CODE REVIEW

**Comment by hhugo** [comment]
@avsm, are you aware of https://github.com/ocaml-ppx/ocaml-migrate-parsetree/issues/50 and https://github.com/hhugo/ocaml-migrate-parsetree/tree/408

**Comment by avsm** [comment]
nope i missed that, thanks! This was just a quick go for me to learn how omp works, so happy to close my PR.  Could I get an answer to the gencopy question though? I'd like to submit the README fixes to the instructions

**Comment by let-def** [comment]
gencopy can be found in copy_parsetree branch: https://github.com/ocaml-ppx/ppx_tools/tree/copy_parsetree

**Comment by avsm** [comment]
I'll close this as the bulk of effort is likely shifting to ppxlib in the future...

**Pull request closed without merging**
