### PR TITLE
Explicitly refer to Result for 4.02

### PR DESCRIPTION
**Pull request by chenglou**
See https://github.com/facebook/reason/pull/1157#issuecomment-288581844

cc @let-def @tekknolagi

### CODE REVIEW

**Comment by tekknolagi** [comment]
And this works for 4.03 and 4.04 as well?

**Comment by chenglou** [comment]
Haven't tested on 4.03+, but qualifying the constructor as such should work? I'll test when I get off the plane

**Comment by tekknolagi** [comment]
lol "should work" 
screenshot from 2017-03-25 17-38-01

**Comment by let-def** [comment]
Hmm, I don't think this is the right direction.
This problem is fixed for 4.02 by passing `-open Result` to the compiler, so that omp is compatible with 4.02 without cluttering later versions.
Maybe you should can do the same with your build system?

**Comment by chenglou** [comment]
Our bundling tool in Reason doesn't have `-open`. We can get by with a sed for now.

**Pull request closed without merging**
