### PR TITLE
Synchronize with trunk.

### PR DESCRIPTION
**Pull request by xclerc**
Fixes compilation with trunk / 4.06.

### CODE REVIEW

**Review by let-def — APPROVED** [review]
I am happy with the code. I resynced with current trunk.

**Comment by let-def** [comment]
@xclerc: Thanks for the PR. I synced to latest trunk on top of your work, if you don't have any objection to this patch I will merge.

**Comment by xclerc** [comment]
No objection - you can merge.

**Comment by let-def** [comment]
Thank you!

**Pull request merged**
