### PR TITLE
Add ocamlfind to opam

### PR DESCRIPTION
**Pull request by yunxing**
ocamlfind is needed in order to find result.

### CODE REVIEW

**Comment by ghost** [comment]
You shouldn't need ocamlfind when installing via opam since result will be installed at the standard library location and jbuilder will be able to find it. @yunxing what error did you get before this patch?

**Comment by let-def** [comment]
I am considering a first release candidate. But I would like to understand this problem better before. @yunxing could you tell us what was the error?

**Comment by yunxing** [comment]
Missed this message earlier. 

It's not an issue with opam install., but an issue with our npm conversion (we are converting this package to npm from opam). In the conversion all packages are installed in a custom location (node_modules), thus we need ocamfind to find it. 

This is my first time running into a problem like this -- I wonder why we don't see this issue in other packages that we converted. Maybe it's something to do with jBuilder?

**Comment by ghost** [comment]
The idea is that when installing a package from opam, Jbuilder doesn't need ocamlfind since libraries are installed at a standard location: `opam config var lib`.

However, if ocamlfind is installed it still asks it for additional search paths using `ocamlfind printconf path`, just in case you are not using opam or have a specific setup such as `node_modules`.

@yunxing, how do you tell ocamlfind to look for packages in `node_modules`? Do you set the environment variable `OCAMLPATH`? In this case I can simply adapt Jbuilder so that it reads this variable as well.

**Comment by yunxing** [comment]
@diml ah that explains it, thanks. 

We use the variable $FINDLIB to look for paths. Each package will have it's own item the the list. 

As an example, we set the environment variable for the package "react" by:
export FINDLIB="/Users/yunxing/reason/node_modules/react/_build/ocamlfind/lib:$FINDLIB"

**Comment by ghost** [comment]
I see. And is FINDLIB interpreted by a custom tool? `man findlib.conf` doesn't mention this variable

**Pull request merged**
