### PR TITLE
Fix handling of `--impl/--intf`

### PR DESCRIPTION
**Pull request by ghost**
Currently, if the extension of the filename passed as argument of `--impl` or `--intf` is neither `.ml` nor `.mli`, the driver fails with the following error:

```
 Error: I can't decide whether parser__mock.ml.mock is an implementation or interface file
```

This PR adds a regression test and fixes the issue.

### CODE REVIEW

**Comment by let-def** [comment]
This looks nice, thanks :)

**Comment by let-def** [comment]
Do you want to make a release soon?

**Comment by ghost** [comment]
Yep, we need this for the new menhir rules which should be in the next release of Dune,

**Comment by fpottier** [comment]
I will soon make a PR with the new Menhir rules.

**Comment by ghost** [comment]
Cool, I'm preparing a minor release of omp.

**Comment by ghost** [comment]
https://github.com/ocaml/opam-repository/pull/12123

**Pull request merged**
