### PR TITLE
Test ocaml-migrate-parsetree-ocamlbuild on Travis

### PR DESCRIPTION
**Pull request by dra27**

### CODE REVIEW

**Comment by dra27** [comment]
Not sure whether this tests the `ocaml-migrate-parsetree-ocamlbuild` from the pull request or from opam, so trying it initially...

**Comment by ghost** [comment]
Shouldn't we move `PACKAGE=xxx` from `global:` to `matrix:` and test both cases?

**Comment by dra27** [comment]
I guess so - it seems to be a limitation of the ocaml-ci-scripts tests.

**Comment by dra27** [comment]
There go another few rainforests on the altar of another stupid yaml file! I think that's doing what's wanted... I also added 4.07.1 testing while I was there

**Comment by ghost** [comment]
I'm thinking that at this point we might just delete this package. It's probably being less and less used and the code pretty much never changed. It doesn't seem worth testing it continously.

**Comment by ghost** [comment]
in fact:

```
$ opam list --depends-on ocaml-migrate-parsetree-ocamlbuild
# Packages matching: (installed | available) & depends-on(ocaml-migrate-parsetree-ocamlbuild)
# No matches found
```

**Comment by dra27** [comment]
My only reservation is that this only tells you what opam-repository is doing - one gets no indication of its use by other non-visible opam remotes.

I've identified the problem - it's when Dune stopped depending on ocamlfind, so if you need the ocamlbuild on 4.02.3 then you need to be sure that ocamlfind is installed. I'll propose it on the opam-repository PR too.

**Comment by ghost** [comment]
It doesn't seem worth making our life harder in this case. I'll create a PR to get rid of the ocamlbuild plugin.

**Pull request closed without merging**
